import type { Metadata } from "next";
import "@mantine/core/styles/global.css";
import "@mantine/core/styles.css";
import "./global.css";
import {
	ColorSchemeScript,
	MantineProvider,
} from "@mantine/core";
import { theme } from "@/themes/global-theme";
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

type ReactChildren = Readonly<{
	children: React.ReactNode;
}>;

export default function RootLayout({
	children,
}: ReactChildren) {
	return (
		<html lang="en">
			<head>
				<ColorSchemeScript />
				<link
					rel="shortcut icon"
					href="/app/favicon.svg"
				/>
				<meta
					name="viewport"
					content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
				/>
			</head>
			<body>
				<MantineProvider
					theme={theme}
					withCssVariables={true}
				>
					{children}
				</MantineProvider>
			</body>
		</html>
	);
}
